from heap import Heap
from heap import heap_sort

heap = Heap()

heap.insert(15)
print(heap)
heap.insert(10)
print(heap)
heap.insert(20)
print(heap)
heap.insert(8)
print(heap)
heap.insert(25)
print(heap)
heap.insert(3)
print(heap)
print(heap.extract_min())
print(heap)
print(heap.extract_min())
print(heap)
print(heap.extract_min())
print(heap)
heap.build_heap([42, 18, 7, 35, 12, 50, 3, 27])
print(heap)
heap.decrease_key(5, 1)
print(heap)
heap.delete(2)
print(heap)
print(heap_sort([64, 34, 25, 12, 22, 11, 90]))
